services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    ports:
      - '8000:8000'
    command: flask --debug run --host=0.0.0.0 --port=8000
    volumes:
      - ./app:/app
    env_file:
      - app.env
      - postgres.env
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./build/postgres/Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - postgres.env
